export const REQUEST_PRODUCTS_LIST = 'REQUEST_PRODUCTS_LIST'
export const REQUEST_PRODUCTS_LIST_SUCCESS = 'REQUEST_PRODUCTS_LIST_SUCCESS'
export const REQUEST_PRODUCTS_LIST_FAIL = 'REQUEST_PRODUCTS_LIST_FAIL'

export const REQUEST_REMOVE_PRODUCT = 'REQUEST_REMOVE_PRODUCT'
export const REQUEST_REMOVE_PRODUCT_SUCCESS = 'REQUEST_REMOVE_PRODUCT_SUCCESS'
export const REQUEST_REMOVE_PRODUCT_FAIL = 'REQUEST_REMOVE_PRODUCT_FAIL'